[build]
  # This will be run the site build
  command = "yarn install && cd client && yarn install && yarn build"
  # This is the directory is publishing to netlify's CDN
  publish = "./client/build"
  # functions build directory
  functions = "functions-build"