[build]
  # This will be run the site build
  command = "cd client && yarn build"
  # This is the directory is publishing to netlify's CDN
  publish = "./client/build"
  # functions build directory
  functions = "functions-build"