
export const FETCH_LISTINGS_INITIATED = 'FETCH_LISTINGS_INITIATED';
export const FETCH_LISTINGS_SUCCESS = 'FETCH_LISTINGS_SUCCESS';
export const FETCH_LISTINGS_FAILURE = 'FETCH_LISTINGS_FAILED';

export const FETCH_JOB_DETAILS_INITIATED = 'FETCH_LISTINGS_DETAILS_INITIATED';
export const FETCH_JOB_DETAILS_SUCCESS = 'FETCH_LISTINGS_DETAILS_SUCCESS';
export const FETCH_JOB_DETAILS_FAILURE = 'FETCH_LISTINGS_DETAILS_FAILED';

export const JOB_APPLICATION_SUBMITTED = 'JOB_APPLICATION_SUBMITTED';
export const JOB_APPLICATION_FILE_UPLOAD = 'JOB_APPLICATION_FILE_UPLOAD';